### ISSUE TITLE
How to set up local peer to peer game of bomberman?

### ISSUE THREAD

**Issue by quantuminformation** [internaut/p2p-bomberman#6]
Firstly thanks for sharing such a cool project! I'm attempting an RTS game with WebRTC.

I was wondering if you could provide instructions to set up a local peer to peer test the game.

![image](https://cloud.githubusercontent.com/assets/216566/12230006/f535f01e-b844-11e5-9c80-2ff920c7c7dd.png)

I am also not able to edit the name here.

**Comment by internaut** [comment]
See https://github.com/internaut/p2p-bomberman#setting-up-a-game-on-your-own-server. You need to run a PeerJS server. You can also do that locally on your computer. Check out [PeerJS](http://peerjs.com/) for that.

**Comment by quantuminformation** [comment]
Thanks, but I was trying this on your demo server.

**Comment by internaut** [comment]
Sorry, but the PeerJS service is not online on the demo server any more, that's why it's not working.
You need to set up the PeerJS service locally on your computer.
